services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: assetdb
      POSTGRES_PASSWORD: assetdb
      POSTGRES_DB: assetdb
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: